name: docker release
on:
  - release
jobs:
  test-unit:
    strategy:
      matrix:
        go-version: [1.15]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build
        run: |
          make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish to Registry - Release
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: negasus/ip2location
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
          dockerfile: Dockerfile

      - name: Publish to Registry - Latest
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: negasus/ip2location
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
          dockerfile: Dockerfile
